### ISSUE TITLE
Error 100: AWS CPI maximum disk size is 1 TiB

### ISSUE THREAD

**Issue by amulyas** [cloudfoundry-incubator/bosh-aws-cpi-release#20]
Can we have this check removed as now AWS allow 16 TB of EBS volume

**Comment by cppforlife** [comment]
@amulyas sounds reasonable. we should just kill of min/max validation (e.g. 'AWS CPI minimum/maximum disk size is X GiB').

cc @ryantang

**Comment by ryantang** [comment]
Thanks @amulyas, @cppforlife .  Here's the [story](https://www.pivotaltracker.com/story/show/111548766) in Pivotal Tracker.

**Comment by amulyas** [comment]
thanks @cppforlife and @ryantang .. you all rocks

**Comment by amulyas** [comment]
I think its already taken care of for gp2 type drives 

    context 'when disk size is greater than 16 TiB' do
      let(:disk_size) { 1025 * 17 * 1000 }

      context 'when disk type is gp2' do
        let(:cloud_properties) { { 'type' => 'gp2' } }

        it 'raises an error' do
          expect {
            cloud.create_disk(disk_size, cloud_properties, 42)
          }.to raise_error /AWS CPI maximum disk size is 16 TiB/
        end
      end

**Comment by cppforlife** [comment]
@amulyas removed in v42.

**Comment by amulyas** [comment]
thanks @cppforlife @ryantang
