### ISSUE TITLE
Creating snapshot is timing out

### ISSUE THREAD

**Issue by bodymindarts** [cloudfoundry-incubator/bosh-aws-cpi-release#21]
When uploading a stemcell sometimes creating a snapshot times out. The time is hard coded by determining the number of retries [here](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/src/bosh_aws_cpi/lib/cloud/aws/resource_wait.rb#L106)
Can we remove this number being passed in and simply use the `DEFAULT_TRIES` like in all the other wait methods?

**Comment by bodymindarts** [comment]
PR created https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/pull/22

**Comment by pmilewsk** [comment]
+1

**Comment by cppforlife** [comment]
Included in v50.
