### ISSUE TITLE
where is the right place to post issues with CloudFoundry bootstrap procedure?

### ISSUE THREAD

**Issue by hakamadare** [cloudfoundry-incubator/bosh-aws-cpi-release#31]
Hello!  I posted cloudfoundry-community/bosh-cloudfoundry#284 and then noticed someone saying that project was no longer maintained.  Where is the appropriate place for me to post the issue that I linked above?

**Comment by ljfranklin** [comment]
@hakamadare That's a good question. Posting the issue to [bosh](https://github.com/cloudfoundry/bosh/issues) seems like right place. You could also ask in the #infrastructure channel at cloudfoundry.slack.com, I think they've been working on something related to bootstrapping on AWS. Feel free to re-open if you don't have any luck in those places.
