### ISSUE TITLE
Packaged Bundler version doesn't match Gemfile.lock version

### ISSUE THREAD

**Issue by sneal** [cloudfoundry-incubator/bosh-aws-cpi-release#40]
The [packaged Bundler version is 1.11.2](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/packages/ruby_aws_cpi/packaging#L35), however the [CPI was bundled with Bundler version 1.12.5](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/src/bosh_aws_cpi/Gemfile.lock#L65). This produces a warning on my system:

```
'Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
```

I think this warning is breaking the CPI because its attempting to [parse the stdout as JSON](https://github.com/cloudfoundry/bosh-init/blob/master/cloud/cpi_cmd_runner.go#L106):

```
Command 'deploy' failed:
  creating stemcell (bosh-aws-xen-hvm-ubuntu-trusty-go_agent 3262.12):
    Unmarshalling external CPI command output: STDOUT: 'Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
{"result":"ami-983cecf8 light","error":null,"log":""}', STDERR: 'I, [2016-10-15T01:37:12.120032 #2308]  INFO -- : [AWS EC2 200 18.312085 0 retries] describe_regions()

I, [2016-10-15T01:37:12.948406 #2308]  INFO -- : [AWS EC2 200 0.828374 0 retries] describe_images(:filters=>[{:name=>"image-id",:values=>["ami-79b26618","ami-4d1fca23","ami-b671aad5","ami-fe47769d","ami-7b4ab914","ami-fcabd78f","ami-3c8b1b50","ami-36c0b421","ami-e78bc787","ami-983cecf8"]}])

':
      invalid character 'W' looking for beginning of value

```

This could be because I have BOSH_INIT_LOG_LEVEL set to DEBUG or it could be for other reasons TBD.

**Comment by ljfranklin** [comment]
@sneal that is interesting. We don't see this in CI on Linux workers or on our OSX workstation using AWS CPI v60. Although the bundler mismatch is an easy fix, but we'd like to reproduce the error first if possible. Which OS and CPI version are you using?

**Comment by cppforlife** [comment]
@sneal bump for os/cpi versions.

**Comment by cppforlife** [comment]
Closing. Feel free to reopen if you see this problem again.
