### ISSUE TITLE
Heavy and Light Stemcell names differ

### ISSUE THREAD

**Issue by friegger** [cloudfoundry-incubator/bosh-aws-cpi-release#43]
Heavy and light stemcell names in stemcell.MF differ for the AWS stemcells:
```
Light name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
Heavy name: bosh-aws-xen-ubuntu-trusty-go_agent
```

Our understanding is, that they should represent the same stemcell inside bosh, which checks for name and version. In the Google Stemcells, the name is the same.

**Comment by cppforlife** [comment]
heavy one is not hvm. we have a story at the top of the backlog to switch over heavies to hvm.
