### ISSUE TITLE
Resource tagging can produce an endless loop

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry-incubator/bosh-aws-cpi-release#50]
When working for the pull request https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/pull/49 I noticed that the [tags method](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/d4eb7d46af19a7e5d1700d53d6d2dd4df103083f/src/bosh_aws_cpi/lib/cloud/aws/tag_manager.rb#L14) in the `tag_manager` can produce an endless loop. If the taggable resource is not found for what ever reason (infrastructure issue) tagging will be retried forever. Does it make sense to add a max number of retries here?

**Comment by cppforlife** [comment]
@beyhan talking about retry (https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/d4eb7d46af19a7e5d1700d53d6d2dd4df103083f/src/bosh_aws_cpi/lib/cloud/aws/tag_manager.rb#L26) i assume? probably makes sense to use bounded retry logic.

**Comment by beyhan** [comment]
@cppforlife yes

**Comment by cppforlife** [comment]
sure does in our ci =)

**Comment by cdutra** [comment]
@cppforlife @beyhan We have a story in our icebox for that: https://www.pivotaltracker.com/story/show/144225287

**Comment by cppforlife** [comment]
fixed in v65.
