### ISSUE TITLE
CPI should redact user-data in create_vm calls

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry-incubator/bosh-aws-cpi-release#56]
As it contains passwords and stuff.

**Comment by cdutra** [comment]
@voelzmo Could you provide more details on this issue, please?

**Comment by voelzmo** [comment]
User data is base64 encoded, but that's it. In the CPIs log output you don't redact it. Therefore, things like nats password are readable for anyone with log access.

You can check the redacted logging in the openstack CPI for some ideas what to redact or talk to @cppforlife for some context.

Warm regards,
Marco

On 27. Jun 2017, at 00:20, Chris Dutra <notifications@github.com<mailto:notifications@github.com>> wrote:


@voelzmo<https://github.com/voelzmo> Could you provide more details on this issue, please?

-

**Comment by cppforlife** [comment]
story: https://www.pivotaltracker.com/story/show/148715311

**Comment by cdutra** [comment]
Story was accepted. Closing this issue.
