### ISSUE TITLE
Package all the dependencies

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bosh-aws-cpi-release#6]
AFAICT, the ruby package makes assumptions about the host machine. In the past, these were probably met by bosh stemcells. But with bosh-init this CPI and its ruby package will be installed on unprepared OS X & Linux machines. Perhaps they should be converted into packages for this (and the openstack) release?

For Ubuntu the packages required are:

```
build-essential zlibc zlib1g-dev \  
  openssl libxslt-dev libxml2-dev libssl-dev \
  libreadline6 libreadline6-dev libyaml-dev libsqlite3-dev sqlite3
```

**Comment by cppforlife** [comment]
Do you think that AWS CPI's ruby package should run this command?

**Comment by calebamiles** [comment]
I would imagine that we could bundle the dependencies that used to be installed in the stemcell into a separate release that bosh-init would use when compiling releases. To me this is a generic issue with bosh-init, perhaps we can move discussion over to the bosh-init repository?

**Comment by cppforlife** [comment]
Documented deps in http://bosh.io/docs/install-bosh-init.html. Reopen in bosh-init if you think we should do something else.
