### ISSUE TITLE
In Cloud Formation; -- Request limit exceeded. (Service: AmazonEC2; Status Code: 503; Error Code: RequestLimitExceeded; Request ID: 7fd6cf20-2880-4845-a2f5-3fa30583767f)

### ISSUE THREAD

**Issue by sureshbabur** [cloudfoundry-incubator/bosh-aws-cpi-release#61]
Hi, I'm trying to create the stack in Cloud formation with 15 beanstalk applications. I've successfully added 13 app and tested with CF and also got the successful result. But if I'm going to add 14th app, then I'm getting the below error randomly. 

19:32:04 UTC+0550 | CREATE_FAILED | AWS::ElasticBeanstalk::Environment | envsocureactionauditprod1515 | Request limit exceeded. (Service: AmazonEC2; Status Code: 503; Error Code: RequestLimitExceeded; Request ID: 7fd6cf20-2880-4845-a2f5-3fa30583767f)

I've checked and already increased the EC2, ASG and CLB limit. But I don't know why I'm getting this error. Anyone help me on this issue.

**Comment by cppforlife** [comment]
@sureshbabur seems like you ended in repo by mistake as it sounds like you have a cloud formation question. i would recommend contacting aws support with a request to up your quota.

**Comment by sureshbabur** [comment]
@cppforlife, I already increased the EC2, ASG and CLB limit. But still I'm getting the an error

**Comment by dpb587-pivotal** [comment]
@sureshbabur the error is not for a specific product limit, but the API usage in general. You'll need to follow up with AWS Support or reduce the rate at which your CloudFormation is provisioning resources.
