### ISSUE TITLE
Ruby version mismatch between tests and `ruby_aws_cpi` package

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry-incubator/bosh-aws-cpi-release#64]
AWS CPI package `ruby_aws_cpi` requires [ruby 2.2.4](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/packages/ruby_aws_cpi/spec#L5). [Tests expect a different version](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/d90cc5d67caf9ec14fbc76af47b94d7a336432d9/src/bosh_aws_cpi/spec/spec_helper.rb#L9) as default and `.envrc` exports as `PROJECT_RUBY_VERSION` ruby 2.1.2. Is this expected?

**Comment by cdutra** [comment]
Hi @beyhan , that was a mistake. We're in the process of upgrading to ruby 2.4.2 from https://github.com/bosh-packages/ruby-release
