### ISSUE TITLE
spot request being cancelled immediately

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bosh-aws-cpi-release#67]
I'm attempting to use a spot bid in my `bosh create-env`; but although `bosh create-env` says it is waiting for the instance, instead AWS thinks the bid was immediately cancelled.

![screen shot 2017-11-01 at 10 03 43 am](https://user-images.githubusercontent.com/108/32254364-0e1cd21e-beec-11e7-8ef5-5dcf77ae2159.png)

To my `bosh create-env -o bosh-deployment/aws/cpi.yml` I've added the following operation:

```
- type: replace
  path: /resource_pools/name=vms/cloud_properties/spot_bid_price?
  value: 0.05
```

Can you think of reasons the aws cpi might be immediately cancelling the spot request?

The first time I attempted this, I waited and got this error:

```
Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'ami-1084a875 light':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::VMCreationFailed","message":"Spot instance creation failed: #\u003cBosh::Clouds::VMCreationFailed: Timed out waiting for spot request #\u003cstruct Aws::EC2::Types::RequestSpotInstancesResult spot_instance_requests=[#\u003cstruct Aws::EC2::Types::SpotInstanceRequest actual_block_hourly_price=nil, availability_zone_group=nil, block_duration_minutes=nil, create_time=2017-10-31 23:54:11 UTC, fault=nil, instance_id=nil, launch_group=nil, launch_specification=#\u003cstruct Aws::EC2::Types::LaunchSpecification user_data=nil, security_groups=[#\u003cstruct Aws::EC2::Types::GroupIdentifier group_name=\"default\", group_id=nil\u003e], addressing_type=nil, block_device_mappings=[#\u003cstruct Aws::EC2::Types::BlockDeviceMapping device_name=\"/dev/sdb\", virtual_name=nil, ebs=#\u003cstruct Aws::EC2::Types::EbsBlockDevice encrypted=nil, delete_on_termination=true, iops=nil, snapshot_id=nil, volume_size=25, volume_type=\"gp2\"\u003e, no_device=nil\u003e, #\u003cstruct Aws::EC2::Types::BlockDeviceMapping device_name=\"/dev/xvda\", virtual_name=nil, ebs=#\u003cstruct Aws::EC2::Types::EbsBlockDevice encrypted=nil, delete_on_termination=true, iops=nil, snapshot_id=nil, volume_size=nil, volume_type=\"gp2\"\u003e, no_device=nil\u003e], ebs_optimized=nil, iam_instance_profile=nil, image_id=\"ami-1084a875\", instance_type=\"m4.xlarge\", kernel_id=nil, key_name=\"admin-community-ohio\", network_interfaces=[#\u003cstruct Aws::EC2::Types::InstanceNetworkInterfaceSpecification associate_public_ip_address=nil, delete_on_termination=nil, description=nil, device_index=0, groups=[], ipv_6_address_count=nil, ipv_6_addresses=[], network_interface_id=nil, private_ip_address=\"10.10.1.4\", private_ip_addresses=[], secondary_private_ip_address_count=nil, subnet_id=\"subnet-d7aef4ac\"\u003e], placement=#\u003cstruct Aws::EC2::Types::SpotPlacement availability_zone=\"us-east-2b\", group_name=nil, tenancy=nil\u003e, ramdisk_id=nil, subnet_id=nil, monitoring=#\u003cstruct Aws::EC2::Types::RunInstancesMonitoringEnabled enabled=false\u003e\u003e, launched_availability_zone=nil, product_description=\"Linux/UNIX\", spot_instance_request_id=\"sir-y28rr38h\", spot_price=\"0.030000\", state=\"open\", status=#\u003cstruct Aws::EC2::Types::SpotInstanceStatus code=\"pending-evaluation\", message=\"Your Spot request has been submitted for review, and is pending evaluation.\", update_time=2017-10-31 23:54:11 UTC\u003e, tags=[], type=\"one-time\", valid_from=nil, valid_until=nil\u003e]\u003e to be fulfilled.\u003e","ok_to_retry":false}
```

I'm not yet sure how `Your Spot request has been submitted for review, and is pending evaluation` relates to to the aws console status of `canceled-before-fulfillment: Your Spot request is canceled before it was fulfilled. `

I was able to manually create a spot instance:

![screen shot 2017-11-01 at 10 13 48 am](https://user-images.githubusercontent.com/108/32254589-60238b10-beed-11e7-994a-796b2b77cf56.png)

**Comment by dpb587-pivotal** [comment]
Spot requests sometimes take an abnormally long time to fulfill (which is where the "pending evaluation" part comes in). The CPI's `create_vm` call timed out on that status and then automatically tried to clean up and cancel the outstanding request.

**Comment by drnic** [comment]
I can reproduce AWS automatically cancelling my manual spot instance requests. No idea why yet.

![screen shot 2017-11-01 at 10 18 09 am](https://user-images.githubusercontent.com/108/32254673-0bd7ff0e-beee-11e7-90c1-9566863898fd.png)

**Comment by dpb587-pivotal** [comment]
Are you sure it's AWS canceling it and not the CPi? Might want to try grep'ing the CPI logs for something like `cancel_spot_instance_requests`.

**Comment by drnic** [comment]
The top three items in the recent screenshot were from manual requests using the AWS Console. The bottom three were from the CPI.

**Comment by dpb587-pivotal** [comment]
Ah, I see. That sounds familiar. Do you have sufficient quota limits for the counts/types you're looking for?

**Comment by drnic** [comment]
I'm playing in a new region (for this account); and it was a request for an m4.xlarge to replace a previously running m4.xlarge; so I don't think its a quota issue. But I've never used spot instances before so I'm unsure if there's something I'm supposed to do first. But I'd have thought the AWS console "Request Spot Instances" wizard would "just work".

**Comment by dpb587-pivotal** [comment]
Odd. Perhaps raise a support ticket to see if they're doing any odd throttling on the account.

**Comment by cdutra** [comment]
@drnic What version of AWS CPI are you using? Also, could you provide `bosh task <id> --debug or --cpi` (be aware of sensitive data. Thanks

**Comment by drnic** [comment]
Issue resolved. Was a bug in my AWS account.

**Comment by davidjstrom** [comment]
Lol. "Issue resolved"
