### ISSUE TITLE
create_vm CPI method not supported

### ISSUE THREAD

**Issue by varun7447** [cloudfoundry-incubator/bosh-aws-cpi-release#71]
For some reason when i try to run the

`bosh -d cf deploy`

i see below error with the latest cf-deployment package

`L Error: Unknown CPI error 'Unknown' with message 'The requested configuration is currently not supported. Please check the documentation for supported configurations.' in 'create_vm' CPI method`

**Comment by dpb587-pivotal** [comment]
This often means you're trying to use an older/newer instance type which is not supported in the availability zone you're using. Perhaps you can double check those values.
