### ISSUE TITLE
Unable to use c5 instance types

### ISSUE THREAD

**Issue by dmlemos** [cloudfoundry-incubator/bosh-aws-cpi-release#77]
When using instance_type `c5.2xlarge`, I get this error:
```
Error: Unknown CPI error 'Unknown' with message 'Enhanced networking with the Elastic Network Adapter (ENA) is required for the 'c5.2xlarge' instance type. Ensure that you are using an AMI that is enabled for ENA.' in 'create_vm' CPI method
```

C5 instances, require specific networking drivers as described [here](https://aws.amazon.com/ec2/instance-types/)

> Besides the error, the deployment seemed to be fine.
**Correction:** Deployment was not fine :sweat_smile:

Stemcell used: `ubuntu trusty 3468.21`

**Comment by cdutra** [comment]
@dmlemos Thanks for filing the issue. Indeed our AMI does not support ENA. When we create AMIs we don't set the `ena_support` flag, and it defaults to `false`.
We added a [story in our backlog](https://www.pivotaltracker.com/story/show/154850804) to add ENA support to our AMIs.

What do you mean by the deployment seems fine? Does the c5.* VMs get created?

cc @jaresty

**Comment by dmlemos** [comment]
Yeah, instances still got created and the monit jobs were good.

**Comment by cdutra** [comment]
@dmlemos That's a behavior that we didn't expect. Was this an upgrade? If yes, what were you upgrading (e.g. instance_type, stemcell etc)?
Could you please provide the output of `bosh task <task-id-for-deployment>` and `bosh tasks --recent=1000 | grep -C5 <task-id-for-deployment>`?

cc @jaresty

**Comment by dmlemos** [comment]
Yes, upgrade from c4 same size.

```sh
$ bosh task 4965
Using environment 'X' as client 'admin'

Task 4965

Task 4965 | 23:30:46 | Preparing deployment: Preparing deployment (00:00:00)
Task 4965 | 23:30:47 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 4965 | 23:30:47 | Updating instance postgres: postgres/c2abff32-e68a-4787-bcab-50c305be1d16 (0) (canary) (00:02:32)
                     L Error: Unknown CPI error 'Unknown' with message 'Enhanced networking with the Elastic Network Adapter (ENA) is required for the 'c5.2xlarge' instance type. Ensure that you are using an AMI that is enabled for ENA.' in 'create_vm' CPI method
Task 4965 | 23:33:19 | Error: Unknown CPI error 'Unknown' with message 'Enhanced networking with the Elastic Network Adapter (ENA) is required for the 'c5.2xlarge' instance type. Ensure that you are using an AMI that is enabled for ENA.' in 'create_vm' CPI method

Task 4965 Started  Wed Jan 31 23:30:46 UTC 2018
Task 4965 Finished Wed Jan 31 23:33:19 UTC 2018
Task 4965 Duration 00:02:33
Task 4965 error

Capturing task '4965' output:
  Expected task '4965' to succeed but state is 'error'

Exit code 1
```

```sh
$ bosh tasks --recent=1000 | grep -C5 '4965'
5017    done            Thu Feb  1 02:00:01 UTC 2018    Thu Feb  1 02:08:56 UTC 2018    scheduler       consul          snapshot deployment                                                     snapshots of deployment 'consul' created
5016    done            Thu Feb  1 02:00:00 UTC 2018    Thu Feb  1 02:07:36 UTC 2018    scheduler       concourse       snapshot deployment                                                     snapshots of deployment 'concourse' created
5015    done            Thu Feb  1 02:00:00 UTC 2018    Thu Feb  1 02:06:44 UTC 2018    scheduler       vault           snapshot deployment                                                     snapshots of deployment 'vault' created
4971    done            Thu Feb  1 00:14:50 UTC 2018    Thu Feb  1 00:22:07 UTC 2018    admin           concourse       create deployment                                                       /deployments/concourse
4965    error           Wed Jan 31 23:30:46 UTC 2018    Wed Jan 31 23:33:19 UTC 2018    admin           concourse       create deployment                                                       Unknown CPI error 'Unknown' with message 'Enhanced networking with the Elastic Network Adapter (ENA) is required for the...
4964    done            Wed Jan 31 02:00:00 UTC 2018    Wed Jan 31 02:07:17 UTC 2018    scheduler       consul          snapshot deployment                                                     snapshots of deployment 'consul' created
4963    done            Wed Jan 31 02:00:00 UTC 2018    Wed Jan 31 02:01:43 UTC 2018    scheduler       concourse       snapshot deployment                                                     snapshots of deployment 'concourse' created
4962    done            Wed Jan 31 02:00:00 UTC 2018    Wed Jan 31 02:05:37 UTC 2018    scheduler       vault           snapshot deployment                                                     snapshots of deployment 'vault' created
4933    done            Wed Jan 31 01:02:09 UTC 2018    Wed Jan 31 01:06:37 UTC 2018    admin           concourse       create deployment                                                       /deployments/concourse
4908    done            Wed Jan 31 00:33:16 UTC 2018    Wed Jan 31 00:37:01 UTC 2018    admin           concourse       create deployment                                                       /deployments/concourse
```

Task `4971` is when I changed the instance size to the same size as before to avoid inconsistent state on BOSH.

**Comment by cdutra** [comment]
This shows that your deployment failed and your VM wasn't upgraded from c4 to c5.
We'll talk to @cppforlife to prioritize the story.

cc @jaresty

**Comment by dmlemos** [comment]
You are correct! That was stupid of me. Thought it had deployed even with errors, but turns out the reason it worked is because HM kicked in and deployed the old instance type 😇

**Comment by ljfranklin** [comment]
+1 we just hit this with `m5` instances as well

**Comment by kitsirota** [comment]
+1 for c5/m5 instances.  

Any updates on this would be super helpful!

**Comment by tjvman** [comment]
In addition to the story @cdutra linked there are two other stories related to this issue:
[Add ENA Support](https://www.pivotaltracker.com/n/projects/1133984/stories/154977267) which will enable instance types that have support to enable it.
We also have: [Agent should look for NVME devices](https://www.pivotaltracker.com/n/projects/956238/stories/152934904), which some of these instance types require for their disks.

**Comment by jdesulme** [comment]
+1 for C5/M5 instances. We tried to use the latest instance types and found out at the wrong time that it wasn't supported yet.

**Comment by cppforlife** [comment]
cc @dsboulder

**Comment by malginin** [comment]
Every CF user moving to m5/c5 stands to gain 15%+ performance for the same money. Rolling out compatibility for these types of instances is the best improvement in terms of performance gain/effort you can make today. Maybe I'm oversimplifying, but this whole thing is mostly about including a pair of drivers in the stemcells and setting the flags right. The fact that this issue hasn't gotten any traction in almost three months (or, to be precise, more than 5 months since gen5 instances were made available) is ludicrous.

**Comment by dpb587-pivotal** [comment]
@cppforlife, can you comment on the priority/timeline of this? And, to help contributors gauge if it's worth their time and priorities to contribute support on their own, speak to the requirements of us accepting a pull request?

**Comment by cppforlife** [comment]
we haven't had a chance to address this yet outside of doing initial investigation and finding out that it's a bit more involved due to disk management change that needs to happen in the agent. i dont have any exact dates but we should have some time soon to address this issue as we are finishing up some of the long running work we have been doing. will update this issue when we start.

> And, to help contributors gauge if it's worth their time and priorities to contribute support on their own, speak to the requirements of us accepting a pull request?

would be happy to receive contribution in this area. if anyone is interested, just let us know. im not sure all the pieces which might have to be changed (cpi + agent) so i dont really have any specific requirements other than components must continue to work with existing stemcells.

**Comment by djvdorp** [comment]
Potentially useful information here: https://aws.amazon.com/premiumsupport/knowledge-center/boot-error-linux-m5-c5/ (most of it is already in https://www.pivotaltracker.com/n/projects/1133984/stories/154850804 it seems)

**Comment by dpb587-pivotal** [comment]
This should be supported in the latest versions of Ubuntu Xenial stemcell and AWS CPI release. If you run into new, more specific errors, please feel free to raise a new issue.
