### ISSUE TITLE
feature request: retry registry update

### ISSUE THREAD

**Issue by ionphractal** [cloudfoundry-incubator/bosh-aws-cpi-release#79]
In one of our systems we noticed that (automated) bosh deployments may fail with
```
Bosh::Clouds::CloudError: CPI error ''Bosh::Clouds::CloudError'' with message ''Cannot update settings for ''i-04f7cada39581ccc7'', got HTTP 500'' in ''create_vm'' CPI method
```
There's also a "Failed to create instance" message which may be a little confusing because creation itself worked (-> should be in a different exception block than the CPI interactions?).
https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/733db1cc02c626fdc39dc73eda804d8e0402e5ef/src/bosh_aws_cpi/lib/cloud/aws/cloud.rb#L152-L156

The registry log shows that the PG (RDS instance) connection broke down.
```
E, [2018-02-28T09:06:23.487976 #5421] ERROR -- : PG::Error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.: SELECT * FROM "registry_instances" WHERE ("instance_id" = 'i-04f7cada39581ccc7') LIMIT 1
```

As this can happen and other CPI related methods have retry methods already, it would be great to have one for the registry update, too.

**Comment by dpb587-pivotal** [comment]
Hi - thanks for documenting this very clearly. A retry does seem like it would be safe to perform, however we probably won't spend much time on investigating this for a couple reasons. So far, this error doesn't happen too often that we have heard about (feel free to post more specifics about frequency and more environment details, such as VM/RDS types; other users, too). But, we are also actively working to remove the registry component, so this whole code path will eventually be going away (here are [some notes](https://github.com/cloudfoundry/bosh-notes/blob/master/proposals/registry-removal.md) about that).

If this is a significant concern for you, feel free to make a pull request of it and we'll be able to consider merging and cutting a new version with it.

FYI - it sounds like this error can also happen when the database runs out of disk space according to https://github.com/cloudfoundry/bosh/issues/1773. If that's your case, it may be a trivial fix. Using a more powerful database can often help as well, if you started with a reduced footprint.

**Comment by ionphractal** [comment]
Hi @dpb587-pivotal, thanks for pointing out the proposed/on-going removal of the registry component. Imho the database is scaled sufficiently. But as the error only pops up occasionally and now with the upcoming change in mind, I don't see much added value atm in fixing the old behavior.
